name: Deploy of beta branch to the production bot [night version]

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_BETA}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_BETA}}
          heroku_email: ${{secrets.HEROKU_EMAIL_BETA}}
          remote_branch: "beta"
